### ISSUE TITLE
Insuffient handling of unusual result values

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/OVAL-visualization-as-graph#85]
This traceback occured while evaluating arf file containing 'error' result.
```
Traceback (most recent call last):
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/arf_to_html.py", line 31, in prepare_data
    oval_tree_dict = self.create_dict_of_rule(rule)
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/arf_to_html.py", line 25, in create_dict_of_rule
    return converter.to_JsTree_dict(self.hide_passing_tests)
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/converter.py", line 72, in to_JsTree_dict
    hide_passing_tests) for child in self.tree.children]
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/converter.py", line 72, in <listcomp>
    hide_passing_tests) for child in self.tree.children]
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/converter.py", line 72, in to_JsTree_dict
    hide_passing_tests) for child in self.tree.children]
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/converter.py", line 72, in <listcomp>
    hide_passing_tests) for child in self.tree.children]
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/converter.py", line 72, in to_JsTree_dict
    hide_passing_tests) for child in self.tree.children]
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/converter.py", line 72, in <listcomp>
    hide_passing_tests) for child in self.tree.children]
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/converter.py", line 56, in to_JsTree_dict
    icons = self._get_node_icon()
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/converter.py", line 39, in _get_node_icon
    values = self._get_node_style()
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/converter.py", line 88, in _get_node_style
    out_color = self.negate_bool(self.tree.value)
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/converter.py", line 133, in negate_bool
    return values[str(value)]
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/command_line.py", line 50, in <module>
    arf_to_graph(sys.argv[2:])
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/command_line.py", line 17, in arf_to_graph
    main(ArfToHtml(args))
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/command_line.py", line 42, in main
    results_src = client.prepare_data(answers)
  File "/home/dahaic/RH/git/upstream/dahaic/OVAL-visualization-as-graph/oval_graph/arf_to_html.py", line 40, in prepare_data
    raise ValueError('Rule: "{}" Error: "{}"'.format(rule, error))
ValueError: Rule: "xccdf_org.ssgproject.content_rule_sshd_disable_empty_passwords" Error: "'error'"
```

**Comment by dahaic** [comment]
To reproduce this result, you can run this command as an unprivileged user (haven't checked Fedora):
```
oscap xccdf eval --progress --results-arf arf_error.xml --profile ospp --rule xccdf_org.ssgproject.content_rule_sshd_disable_empty_passwords /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
```
